import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  header: {
    width: 'auto',
    height: 250,
    paddingHorizontal: 18,
    paddingTop: 30,
  },
  headerController: {flexDirection: 'row'},
  back: {marginRight: 'auto'},
  rating: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFCD61',
    width: 50,
    height: 23,
    borderRadius: 30,
    marginRight: 10,
  },
  ratingTxt: {color: 'white'},
  rightHeader: {flexDirection: 'row', alignItems: 'center'},
  container: {
    padding: 18,
  },
  titleContainer: {flexDirection: 'row', marginBottom: 10},
  title: {
    fontSize: 28,
    fontWeight: '500',
    marginRight: 'auto',
  },
  textPadding: {
    paddingVertical: 3,
  },
  greenTxt: {color: 'green', fontWeight: '500', marginBottom: 20},
  location: {
    flexDirection: 'row',
    marginBottom: 13,
    alignItems: 'center',
  },
  locationLogo: {
    width: 38,
    height: 38,
    backgroundColor: 'rgba(255, 199, 167, 0.5)',
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 20,
  },
  grayTxt: {color: '#999999'},
  selector: {
    marginVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  selectorTitle: {
    fontSize: 15,
    fontWeight: '800',
  },
  counter: {flexDirection: 'row', alignItems: 'center'},
  counterBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#FFCD61',
    alignItems: 'center',
    justifyContent: 'center',
  },
  amount: {fontSize: 15, fontWeight: '900', marginHorizontal: 20},
  picker: {flexDirection: 'row'},
  date: {
    backgroundColor: 'rgba(57, 57, 57, 0.1)',
    justifyContent: 'center',
    borderRadius: 10,
    paddingLeft: 16,
    flex: 1,
    marginRight: 20,
  },
  inputAndroid: {
    backgroundColor: 'rgba(57, 57, 57, 0.1)',
    justifyContent: 'center',
    borderRadius: 10,
    paddingHorizontal: 16,
    width: 125,
    color: 'black',
  },
  dropdownIcon: {
    marginVertical: 12,
    paddingRight: 10,
  },
  reserve: {
    marginTop: 20,
    width: 'auto',
    height: 50,
    backgroundColor: '#FFCD61',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reserveDisabled: {
    marginTop: 20,
    width: 'auto',
    height: 50,
    backgroundColor: 'rgba(255, 205, 97, 0.35)',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reserveTxt: {
    fontSize: 20,
    fontWeight: '700',
  },
  disabledReseveTxt: {
    color: 'rgba(0, 0, 0, 0.3)',
  },
  availableTxt: {color: '#087E0D', fontWeight: '700', marginBottom: 5},
  notAvailableTxt: {color: 'red', fontWeight: '700', marginBottom: 5},
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgb(255, 255, 255)',
  },
  countModalContainer: {backgroundColor: 'rgba(0, 0, 0, 0.5)'},
  countModal: {
    backgroundColor: 'white',
    paddingHorizontal: 20,
    paddingVertical: 30,
    borderRadius: 10,
  },
  countModalButton: {
    backgroundColor: '#2196F3',
    alignItems: 'center',
    padding: 5,
    borderRadius: 10,
    marginTop: 20,
  },
});
